=== UO291047/SEW/xml/circuito.dtd
<!ELEMENT circuito (datosCircuito, datosCarrera)>
<!ELEMENT datosCircuito (nombre, medidas, ubicacion, galeria)>
<!ELEMENT datosCarrera (fecha, horaIniEsp, vueltas)>
<!ELEMENT medidas (longitud, anchuraMedia, sectores)>
<!ELEMENT ubicacion (localidad, pais, coords)>
<!ELEMENT galeria (refs, fotos, videos)>
<!ELEMENT anchuraMedia (longitud)>
<!ELEMENT sectores (sector+)>
<!ELEMENT refs (ref+)>
<!ELEMENT fotos (foto+)>
<!ELEMENT videos (video)>
<!ELEMENT sector (longitud, coords, num)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT horaIniEsp (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT coords (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT num (#PCDATA)>
<!ATTLIST longitud
    unidades CDATA #REQUIRED>
<!ATTLIST coords
    longitud CDATA #REQUIRED
    latitud CDATA #REQUIRED
    altitud CDATA #REQUIRED>

=== UO291047/SEW/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>
    <datosCircuito>
        <nombre>Yas Marina</nombre>
        <medidas>
            <longitud unidades="km">5.281</longitud>
            <anchuraMedia><longitud unidades="m">12</longitud></anchuraMedia>
            <sectores>
                <sector>
                    <longitud unidades="m">251.26</longitud>
                    <coords longitud="24.47036529464194" latitud="54.60804048152899" altitud="5"></coords>
                    <num>1</num>
                </sector>
                <sector>
                    <longitud unidades="m">100</longitud>
                    <coords longitud="1" latitud="2" altitud="3"></coords>
                    <num>1</num>
                </sector>
                <sector>
                    <longitud unidades="m">100</longitud>
                    <coords longitud="1" latitud="2" altitud="3"></coords>
                    <num>1</num>
                </sector>
                <sector>
                    <longitud unidades="m">100</longitud>
                    <coords longitud="1" latitud="2" altitud="3"></coords>
                    <num>1</num>
                </sector>
            </sectores>
        </medidas>
        <ubicacion>
            <localidad>Abu Dabi</localidad>
            <pais>Emiratos Arabes</pais>
            <coords longitud="24.470169284798708" latitud="54.60814461806192" altitud="5"></coords>
        </ubicacion>
        <galeria>
            <refs>
                <ref>https://es.wikipedia.org/wiki/Circuito_Yas_Marina</ref>
                <ref>https://www.yasmarinacircuit.com/</ref>
                <ref>http://news.bbc.co.uk/sport2/hi/motorsport/formula_one/7473748.stm</ref>
            </refs>
            <fotos>
                <foto>"../multimedia/imagenes/Yas_Marina_Circuit.png"</foto>
            </fotos>
            <videos>
                <video></video>
            </videos>
        </galeria>
    </datosCircuito>
    <datosCarrera>
        <fecha>8/12/2024</fecha>
        <horaIniEsp>1:00</horaIniEsp>
        <vueltas>58</vueltas>
    </datosCarrera>
</circuito>
